export const DEGREE_TYPES = [
  { value: 'Certificate' },
  { value: 'Diploma' },
  { value: 'Degree' },
  { value: 'Masters' },
  { value: 'PhD' },
  { value: 'Associate Degree' },
  { value: "Bachelor's Degree" },
  { value: 'Postgraduate Diploma' },
  { value: 'Honours Degree' },
  { value: 'Professional Certificate' },
  { value: 'Advanced Diploma' },
  { value: 'Graduate Diploma' },
  { value: 'Doctorate' },
  {
    value: 'Higher National Diploma (HND)'
  },
  { value: 'Vocational Certificate' },
  { value: 'Specialist Diploma' },
  { value: 'Advanced Certificate' },
  { value: 'Licentiate Degree' },
  { value: 'Fellowship Diploma' }
]
export const GENDERS = ['M', 'F']

export const POTENTIAL_LEVELS = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10'
]

export const INDUSTRIES = [
  'Accounting',
  'Agriculture',
  'Automotive',
  'Banking',
  'Biotechnology',
  'Chemical',
  'Construction',
  'Consulting',
  'Education',
  'Engineering',
  'Entertainment',
  'Environmental',
  'Fashion',
  'Finance',
  'Food & Beverage',
  'Government',
  'Healthcare',
  'Hospitality',
  'Insurance',
  'Information Technology',
  'Legal',
  'Manufacturing',
  'Marketing',
  'Media',
  'Non-profit',
  'Pharmaceutical',
  'Real Estate',
  'Retail',
  'Telecommunications',
  'Transportation',
  'Utilities'
]

export const DEFAULT_COMPETENCY_LEVELS = [
  {
    id: '',
    title: 'Entry',
    weight: 1,
    description: ''
  },
  {
    id: '',
    title: 'Beginner',
    weight: 2,
    description: ''
  },
  {
    id: '',
    title: 'Intermediate',
    weight: 3,
    description: ''
  },
  {
    id: '',
    title: 'Advanced',
    weight: 4,
    description: ''
  },
  {
    id: '',
    title: 'Expert',
    weight: 5,
    description: ''
  }
]

export const EXPERIENCE_LEVELS = [
  'Entry',
  'Beginner',
  'Intermediate',
  'Advanced',
  'Expert'
]

export const DEFAULT_SKILLS = [
  'Communication',
  'Problem solving',
  'Teamwork',
  'Time Management',
  'Emotional Intelligence'
]

export const ROLES = ['CEO$', 'MANAGER', 'EMPLOYEE', 'HRD', 'HR']

export const EMPLOYEE_COUNT_SELECTIONS = [
  '1 to 10 employees',
  '11 to 50 employees',
  '51 to 200 employees',
  '201 to 500 employees',
  'more then 500 employees'
]

export enum AUTH_ROLES {
  CEO = 'CEO',
  HDR = 'HRD',
  HR = 'HR',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE'
}

export const DEFAULT_BRAND_IMG_PATH = process.env.DEFAULT_BRAND_IMAGE
export const DEFAULT_PFP_IMG_PATH = process.env.DEFAULT_PFP_IMAGE

export const OBJECTIVES_CATEGORIES = [
  { value: 'Customer Service' },
  { value: 'Productivity Enhancement' },
  { value: 'Sales Growth' },
  { value: 'Cost Reduction' },
  { value: 'Quality Improvement' },
  { value: 'Employee Engagement' },
  { value: 'Leadership Development' },
  { value: 'Innovation Initiatives' },
  { value: 'Training and Development' },
  { value: 'Market Expansion' },
  { value: 'Process Optimization' },
  { value: 'Team Collaboration' },
  { value: 'Time Management' },
  { value: 'Risk Management' },
  { value: 'Sustainability Initiatives' },
  { value: 'Regulatory Compliance' },
  { value: 'Brand Building' },
  { value: 'Technology Integration' },
  { value: 'Health and Safety' },
  { value: 'Financial Performance' },
  { value: 'Customer Satisfaction' },
  { value: 'Employee Satisfaction' },
  { value: 'Work-Life Balance' },
  { value: 'Customer Retention' },
  { value: 'Employee Retention' },
  { value: 'Project Management' },
  { value: 'Problem Solving' },
  { value: 'Communication Skills' },
  { value: 'Conflict Resolution' },
  { value: 'Career Development' },
  { value: 'Workplace Diversity' },
  { value: 'Team Building' },
  { value: 'Strategic Planning' },
  { value: 'Performance Evaluation' },
  { value: 'Change Management' },
  { value: 'Data Analysis' },
  { value: 'Financial Planning' },
  { value: 'Client Relationship Management' },
  { value: 'Supply Chain Management' },
  { value: 'Environmental Sustainability' }
]
export const OBJECTIVES_STATUS = ['Planned', 'Ongoing', 'Done', 'Abandoned']

export const JOB_TYPES = [
  'Full Time',
  'Part Time',
  'Contract',
  'Temporary',
  'Internship',
  'Freelance'
]

export const OBJECTIVE_TYPES = [
  'On-the-Job Training',
  'Mentoring',
  'Coaching',
  'Job Rotation',
  'Skill Development',
  'Goal Setting and Performance Management',
  'Cross-Functional Collaboration',
  'Leadership Development',
  'Continuous Learning and Professional Development',
  'Feedback and Self-Reflection'
]

export const MARITAL_TYPES = [
  'Single',
  'Married',
  'Divorced',
  'Widowed',
  'Separated'
]

export const READINESS_TYPES = [
  '1 to 2 years',
  '3 to 5 years',
  '> 5 years',
  '< 1 year'
]

export const ONBOARDING_SOFT_SKILLS = [
  { id: 'Communication', label: 'Communication' },
  { id: 'Teamwork', label: 'Teamwork' },
  { id: 'Problem Solving', label: 'Problem Solving' },
  { id: 'Time Management', label: 'Time Management' },
  { id: 'Adaptability', label: 'Adaptability' },
  { id: 'Leadership', label: 'Leadership' },
  { id: 'Creativity', label: 'Creativity' },
  { id: 'Emotional Intelligence', label: 'Emotional Intelligence' },
  { id: 'Conflict Resolution', label: 'Conflict Resolution' },
  { id: 'Decision Making', label: 'Decision Making' }
]

export const PRIORITIES = ['Optional', 'Low', 'Medium', 'Hight', 'Critical']

export const LOCALES = ['en', 'fr'] as const

export const PROVINCES = [
  { value: 'Adrar' },
  { value: 'Chlef' },
  { value: 'Laghouat' },
  { value: 'Oum El Bouaghi' },
  { value: 'Batna' },
  { value: 'Béjaïa' },
  { value: 'Biskra' },
  { value: 'Béchar' },
  { value: 'Blida' },
  { value: 'Bouira' },
  { value: 'Tamanrasset' },
  { value: 'Tébessa' },
  { value: 'Tlemcen' },
  { value: 'Tiaret' },
  { value: 'Tizi Ouzou' },
  { value: 'Alger' },
  { value: 'Djelfa' },
  { value: 'Jijel' },
  { value: 'Sétif' },
  { value: 'Saïda' },
  { value: 'Skikda' },
  { value: 'Sidi Bel Abbès' },
  { value: 'Annaba' },
  { value: 'Guelma' },
  { value: 'Constantine' },
  { value: 'Médéa' },
  { value: 'Mostaganem' },
  { value: "M'Sila" },
  { value: 'Mascara' },
  { value: 'Ouargla' },
  { value: 'Oran' },
  { value: 'El Bayadh' },
  { value: 'Illizi' },
  { value: 'Bordj Bou Arreridj' },
  { value: 'Boumerdès' },
  { value: 'El Tarf' },
  { value: 'Tindouf' },
  { value: 'Tissemsilt' },
  { value: 'El Oued' },
  { value: 'Khenchela' },
  { value: 'Souk Ahras' },
  { value: 'Tipaza' },
  { value: 'Mila' },
  { value: 'Aïn Defla' },
  { value: 'Naama' },
  { value: 'Aïn Témouchent' },
  { value: 'Ghardaïa' },
  { value: 'Relizane' },
  { value: 'Timimoun' },
  { value: 'Bordj Badji Mokhtar' },
  { value: ' Ouled  Djellal' },
  { value: 'Béni Abbès' },
  { value: 'In Salah' },
  { value: 'In Guezzam' },
  { value: 'Touggourt' },
  { value: 'Djanet' },
  { value: 'El M’Ghaier' },
  { value: 'El Meniaa' }
]
export const COUNTRIES = [
  { value: 'Afghanistan' },
  { value: 'Albania' },
  { value: 'Algeria' },
  { value: 'Andorra' },
  { value: 'Angola' },
  { value: 'Antigua and Barbuda' },
  { value: 'Argentina' },
  { value: 'Armenia' },
  { value: 'Australia' },
  { value: 'Austria' },
  { value: 'Azerbaijan' },
  { value: 'Bahamas' },
  { value: 'Bahrain' },
  { value: 'Bangladesh' },
  { value: 'Barbados' },
  { value: 'Belarus' },
  { value: 'Belgium' },
  { value: 'Belize' },
  { value: 'Benin' },
  { value: 'Bhutan' },
  { value: 'Bolivia' },
  { value: 'Bosnia and Herzegovina' },
  { value: 'Botswana' },
  { value: 'Brazil' },
  { value: 'Brunei' },
  { value: 'Bulgaria' },
  { value: 'Burkina Faso' },
  { value: 'Burundi' },
  { value: 'Cabo Verde' },
  { value: 'Cambodia' },
  { value: 'Cameroon' },
  { value: 'Canada' },
  { value: 'Central African Republic' },
  { value: 'Chad' },
  { value: 'Chile' },
  { value: 'China' },
  { value: 'Colombia' },
  { value: 'Comoros' },
  { value: 'Congo' },
  { value: 'Costa Rica' },
  { value: 'Croatia' },
  { value: 'Cuba' },
  { value: 'Cyprus' },
  { value: 'Czech Republic' },
  { value: 'Denmark' },
  { value: 'Djibouti' },
  { value: 'Dominica' },
  { value: 'Dominican Republic' },
  { value: 'East Timor' },
  { value: 'Ecuador' },
  { value: 'Egypt' },
  { value: 'El Salvador' },
  { value: 'Equatorial Guinea' },
  { value: 'Eritrea' },
  { value: 'Estonia' },
  { value: 'Eswatini' },
  { value: 'Ethiopia' },
  { value: 'Fiji' },
  { value: 'Finland' },
  { value: 'France' },
  { value: 'Gabon' },
  { value: 'Gambia' },
  { value: 'Georgia' },
  { value: 'Germany' },
  { value: 'Ghana' },
  { value: 'Greece' },
  { value: 'Grenada' },
  { value: 'Guatemala' },
  { value: 'Guinea' },
  { value: 'Guinea-Bissau' },
  { value: 'Guyana' },
  { value: 'Haiti' },
  { value: 'Honduras' },
  { value: 'Hungary' },
  { value: 'Iceland' },
  { value: 'India' },
  { value: 'Indonesia' },
  { value: 'Iran' },
  { value: 'Iraq' },
  { value: 'Ireland' },
  { value: 'Israel' },
  { value: 'Italy' },
  { value: 'Jamaica' },
  { value: 'Japan' },
  { value: 'Jordan' },
  { value: 'Kazakhstan' },
  { value: 'Kenya' },
  { value: 'Kiribati' },
  { value: 'Korea, North' },
  { value: 'Korea, South' },
  { value: 'Kosovo' },
  { value: 'Kuwait' },
  { value: 'Kyrgyzstan' },
  { value: 'Laos' },
  { value: 'Latvia' },
  { value: 'Lebanon' },
  { value: 'Lesotho' },
  { value: 'Liberia' },
  { value: 'Libya' },
  { value: 'Liechtenstein' },
  { value: 'Lithuania' },
  { value: 'Luxembourg' },
  { value: 'Madagascar' },
  { value: 'Malawi' },
  { value: 'Malaysia' },
  { value: 'Maldives' },
  { value: 'Mali' },
  { value: 'Malta' },
  { value: 'Marshall Islands' },
  { value: 'Mauritania' },
  { value: 'Mauritius' },
  { value: 'Mexico' },
  { value: 'Micronesia' },
  { value: 'Moldova' },
  { value: 'Monaco' },
  { value: 'Mongolia' },
  { value: 'Montenegro' },
  { value: 'Morocco' },
  { value: 'Mozambique' },
  { value: 'Myanmar' },
  { value: 'Namibia' },
  { value: 'Nauru' },
  { value: 'Nepal' },
  { value: 'Netherlands' },
  { value: 'New Zealand' },
  { value: 'Nicaragua' },
  { value: 'Niger' },
  { value: 'Nigeria' },
  { value: 'North Macedonia' },
  { value: 'Norway' },
  { value: 'Oman' },
  { value: 'Pakistan' },
  { value: 'Palau' },
  { value: 'Panama' },
  { value: 'Papua New Guinea' },
  { value: 'Paraguay' },
  { value: 'Peru' },
  { value: 'Philippines' },
  { value: 'Poland' },
  { value: 'Portugal' },
  { value: 'Qatar' },
  { value: 'Romania' },
  { value: 'Russia' },
  { value: 'Rwanda' },
  { value: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia' },
  { value: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa' },
  { value: 'San Marino' },
  { value: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia' },
  { value: 'Senegal' },
  { value: 'Serbia' },
  { value: 'Seychelles' },
  { value: 'Sierra Leone' },
  { value: 'Singapore' },
  { value: 'Slovakia' },
  { value: 'Slovenia' },
  { value: 'Solomon Islands' },
  { value: 'Somalia' },
  { value: 'South Africa' },
  { value: 'South Sudan' },
  { value: 'Spain' },
  { value: 'Sri Lanka' },
  { value: 'Sudan' },
  { value: 'Suriname' },
  { value: 'Sweden' },
  { value: 'Switzerland' },
  { value: 'Syria' },
  { value: 'Taiwan' },
  { value: 'Tajikistan' },
  { value: 'Tanzania' },
  { value: 'Thailand' },
  { value: 'Togo' },
  { value: 'Tonga' },
  { value: 'Trinidad and Tobago' },
  { value: 'Tunisia' },
  { value: 'Turkey' },
  { value: 'Turkmenistan' },
  { value: 'Tuvalu' },
  { value: 'Uganda' },
  { value: 'Ukraine' },
  { value: 'United Arab Emirates' },
  { value: 'United Kingdom' },
  { value: 'United States' },
  { value: 'Uruguay' },
  { value: 'Uzbekistan' },
  { value: 'Vanuatu' },
  { value: 'Vatican City' },
  { value: 'Venezuela' },
  { value: 'Vietnam' },
  { value: 'Yemen' },
  { value: 'Zambia' },
  { value: 'Zimbabwe' }
]

export const SUCCESSION_PLAN_STATUS = ['Active', 'On Hold', 'Cancelled']
